export enum SaveStatusEnum{
   ADD_TASK= "ADD_TASK",
   ADD_SUBTASK = "ADD_SUBTASK",
   EDIT_TASK = "EDIT_TASK",
   EDIT_SUBTASK = "EDIT_SUBTASK",
   DELETE_TASK = "DELETE_TASK",
   DELETE_SUBTASK = "DELETE_SUBTASK",
}